/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.saketsaurabh.nbt.measurement;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-04-30")
public class BandwidthWorkRequest implements org.apache.thrift.TBase<BandwidthWorkRequest, BandwidthWorkRequest._Fields>, java.io.Serializable, Cloneable, Comparable<BandwidthWorkRequest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("BandwidthWorkRequest");

  private static final org.apache.thrift.protocol.TField DESTINATION_IP_FIELD_DESC = new org.apache.thrift.protocol.TField("destination_ip", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new BandwidthWorkRequestStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new BandwidthWorkRequestTupleSchemeFactory();

  public java.lang.String destination_ip; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    DESTINATION_IP((short)1, "destination_ip");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DESTINATION_IP
          return DESTINATION_IP;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DESTINATION_IP, new org.apache.thrift.meta_data.FieldMetaData("destination_ip", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(BandwidthWorkRequest.class, metaDataMap);
  }

  public BandwidthWorkRequest() {
  }

  public BandwidthWorkRequest(
    java.lang.String destination_ip)
  {
    this();
    this.destination_ip = destination_ip;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public BandwidthWorkRequest(BandwidthWorkRequest other) {
    if (other.isSetDestination_ip()) {
      this.destination_ip = other.destination_ip;
    }
  }

  public BandwidthWorkRequest deepCopy() {
    return new BandwidthWorkRequest(this);
  }

  @Override
  public void clear() {
    this.destination_ip = null;
  }

  public java.lang.String getDestination_ip() {
    return this.destination_ip;
  }

  public BandwidthWorkRequest setDestination_ip(java.lang.String destination_ip) {
    this.destination_ip = destination_ip;
    return this;
  }

  public void unsetDestination_ip() {
    this.destination_ip = null;
  }

  /** Returns true if field destination_ip is set (has been assigned a value) and false otherwise */
  public boolean isSetDestination_ip() {
    return this.destination_ip != null;
  }

  public void setDestination_ipIsSet(boolean value) {
    if (!value) {
      this.destination_ip = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case DESTINATION_IP:
      if (value == null) {
        unsetDestination_ip();
      } else {
        setDestination_ip((java.lang.String)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case DESTINATION_IP:
      return getDestination_ip();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case DESTINATION_IP:
      return isSetDestination_ip();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof BandwidthWorkRequest)
      return this.equals((BandwidthWorkRequest)that);
    return false;
  }

  public boolean equals(BandwidthWorkRequest that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_destination_ip = true && this.isSetDestination_ip();
    boolean that_present_destination_ip = true && that.isSetDestination_ip();
    if (this_present_destination_ip || that_present_destination_ip) {
      if (!(this_present_destination_ip && that_present_destination_ip))
        return false;
      if (!this.destination_ip.equals(that.destination_ip))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetDestination_ip()) ? 131071 : 524287);
    if (isSetDestination_ip())
      hashCode = hashCode * 8191 + destination_ip.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(BandwidthWorkRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetDestination_ip()).compareTo(other.isSetDestination_ip());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDestination_ip()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.destination_ip, other.destination_ip);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("BandwidthWorkRequest(");
    boolean first = true;

    sb.append("destination_ip:");
    if (this.destination_ip == null) {
      sb.append("null");
    } else {
      sb.append(this.destination_ip);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class BandwidthWorkRequestStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public BandwidthWorkRequestStandardScheme getScheme() {
      return new BandwidthWorkRequestStandardScheme();
    }
  }

  private static class BandwidthWorkRequestStandardScheme extends org.apache.thrift.scheme.StandardScheme<BandwidthWorkRequest> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, BandwidthWorkRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // DESTINATION_IP
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.destination_ip = iprot.readString();
              struct.setDestination_ipIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, BandwidthWorkRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.destination_ip != null) {
        oprot.writeFieldBegin(DESTINATION_IP_FIELD_DESC);
        oprot.writeString(struct.destination_ip);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class BandwidthWorkRequestTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public BandwidthWorkRequestTupleScheme getScheme() {
      return new BandwidthWorkRequestTupleScheme();
    }
  }

  private static class BandwidthWorkRequestTupleScheme extends org.apache.thrift.scheme.TupleScheme<BandwidthWorkRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, BandwidthWorkRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetDestination_ip()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetDestination_ip()) {
        oprot.writeString(struct.destination_ip);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, BandwidthWorkRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.destination_ip = iprot.readString();
        struct.setDestination_ipIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

