/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.saketsaurabh.nbt.reporting;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-04-30")
public class BandwidthMeasurement implements org.apache.thrift.TBase<BandwidthMeasurement, BandwidthMeasurement._Fields>, java.io.Serializable, Cloneable, Comparable<BandwidthMeasurement> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("BandwidthMeasurement");

  private static final org.apache.thrift.protocol.TField SOURCE_IP_FIELD_DESC = new org.apache.thrift.protocol.TField("source_ip", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField DESTINATION_IP_FIELD_DESC = new org.apache.thrift.protocol.TField("destination_ip", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField BANDWIDTH_FIELD_DESC = new org.apache.thrift.protocol.TField("bandwidth", org.apache.thrift.protocol.TType.DOUBLE, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new BandwidthMeasurementStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new BandwidthMeasurementTupleSchemeFactory();

  public java.lang.String source_ip; // required
  public java.lang.String destination_ip; // required
  public double bandwidth; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SOURCE_IP((short)1, "source_ip"),
    DESTINATION_IP((short)2, "destination_ip"),
    BANDWIDTH((short)3, "bandwidth");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SOURCE_IP
          return SOURCE_IP;
        case 2: // DESTINATION_IP
          return DESTINATION_IP;
        case 3: // BANDWIDTH
          return BANDWIDTH;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __BANDWIDTH_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SOURCE_IP, new org.apache.thrift.meta_data.FieldMetaData("source_ip", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DESTINATION_IP, new org.apache.thrift.meta_data.FieldMetaData("destination_ip", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.BANDWIDTH, new org.apache.thrift.meta_data.FieldMetaData("bandwidth", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(BandwidthMeasurement.class, metaDataMap);
  }

  public BandwidthMeasurement() {
  }

  public BandwidthMeasurement(
    java.lang.String source_ip,
    java.lang.String destination_ip,
    double bandwidth)
  {
    this();
    this.source_ip = source_ip;
    this.destination_ip = destination_ip;
    this.bandwidth = bandwidth;
    setBandwidthIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public BandwidthMeasurement(BandwidthMeasurement other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetSource_ip()) {
      this.source_ip = other.source_ip;
    }
    if (other.isSetDestination_ip()) {
      this.destination_ip = other.destination_ip;
    }
    this.bandwidth = other.bandwidth;
  }

  public BandwidthMeasurement deepCopy() {
    return new BandwidthMeasurement(this);
  }

  @Override
  public void clear() {
    this.source_ip = null;
    this.destination_ip = null;
    setBandwidthIsSet(false);
    this.bandwidth = 0.0;
  }

  public java.lang.String getSource_ip() {
    return this.source_ip;
  }

  public BandwidthMeasurement setSource_ip(java.lang.String source_ip) {
    this.source_ip = source_ip;
    return this;
  }

  public void unsetSource_ip() {
    this.source_ip = null;
  }

  /** Returns true if field source_ip is set (has been assigned a value) and false otherwise */
  public boolean isSetSource_ip() {
    return this.source_ip != null;
  }

  public void setSource_ipIsSet(boolean value) {
    if (!value) {
      this.source_ip = null;
    }
  }

  public java.lang.String getDestination_ip() {
    return this.destination_ip;
  }

  public BandwidthMeasurement setDestination_ip(java.lang.String destination_ip) {
    this.destination_ip = destination_ip;
    return this;
  }

  public void unsetDestination_ip() {
    this.destination_ip = null;
  }

  /** Returns true if field destination_ip is set (has been assigned a value) and false otherwise */
  public boolean isSetDestination_ip() {
    return this.destination_ip != null;
  }

  public void setDestination_ipIsSet(boolean value) {
    if (!value) {
      this.destination_ip = null;
    }
  }

  public double getBandwidth() {
    return this.bandwidth;
  }

  public BandwidthMeasurement setBandwidth(double bandwidth) {
    this.bandwidth = bandwidth;
    setBandwidthIsSet(true);
    return this;
  }

  public void unsetBandwidth() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __BANDWIDTH_ISSET_ID);
  }

  /** Returns true if field bandwidth is set (has been assigned a value) and false otherwise */
  public boolean isSetBandwidth() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __BANDWIDTH_ISSET_ID);
  }

  public void setBandwidthIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __BANDWIDTH_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case SOURCE_IP:
      if (value == null) {
        unsetSource_ip();
      } else {
        setSource_ip((java.lang.String)value);
      }
      break;

    case DESTINATION_IP:
      if (value == null) {
        unsetDestination_ip();
      } else {
        setDestination_ip((java.lang.String)value);
      }
      break;

    case BANDWIDTH:
      if (value == null) {
        unsetBandwidth();
      } else {
        setBandwidth((java.lang.Double)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case SOURCE_IP:
      return getSource_ip();

    case DESTINATION_IP:
      return getDestination_ip();

    case BANDWIDTH:
      return getBandwidth();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case SOURCE_IP:
      return isSetSource_ip();
    case DESTINATION_IP:
      return isSetDestination_ip();
    case BANDWIDTH:
      return isSetBandwidth();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof BandwidthMeasurement)
      return this.equals((BandwidthMeasurement)that);
    return false;
  }

  public boolean equals(BandwidthMeasurement that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_source_ip = true && this.isSetSource_ip();
    boolean that_present_source_ip = true && that.isSetSource_ip();
    if (this_present_source_ip || that_present_source_ip) {
      if (!(this_present_source_ip && that_present_source_ip))
        return false;
      if (!this.source_ip.equals(that.source_ip))
        return false;
    }

    boolean this_present_destination_ip = true && this.isSetDestination_ip();
    boolean that_present_destination_ip = true && that.isSetDestination_ip();
    if (this_present_destination_ip || that_present_destination_ip) {
      if (!(this_present_destination_ip && that_present_destination_ip))
        return false;
      if (!this.destination_ip.equals(that.destination_ip))
        return false;
    }

    boolean this_present_bandwidth = true;
    boolean that_present_bandwidth = true;
    if (this_present_bandwidth || that_present_bandwidth) {
      if (!(this_present_bandwidth && that_present_bandwidth))
        return false;
      if (this.bandwidth != that.bandwidth)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetSource_ip()) ? 131071 : 524287);
    if (isSetSource_ip())
      hashCode = hashCode * 8191 + source_ip.hashCode();

    hashCode = hashCode * 8191 + ((isSetDestination_ip()) ? 131071 : 524287);
    if (isSetDestination_ip())
      hashCode = hashCode * 8191 + destination_ip.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(bandwidth);

    return hashCode;
  }

  @Override
  public int compareTo(BandwidthMeasurement other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetSource_ip()).compareTo(other.isSetSource_ip());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSource_ip()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.source_ip, other.source_ip);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetDestination_ip()).compareTo(other.isSetDestination_ip());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDestination_ip()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.destination_ip, other.destination_ip);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetBandwidth()).compareTo(other.isSetBandwidth());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBandwidth()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.bandwidth, other.bandwidth);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("BandwidthMeasurement(");
    boolean first = true;

    sb.append("source_ip:");
    if (this.source_ip == null) {
      sb.append("null");
    } else {
      sb.append(this.source_ip);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("destination_ip:");
    if (this.destination_ip == null) {
      sb.append("null");
    } else {
      sb.append(this.destination_ip);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("bandwidth:");
    sb.append(this.bandwidth);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class BandwidthMeasurementStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public BandwidthMeasurementStandardScheme getScheme() {
      return new BandwidthMeasurementStandardScheme();
    }
  }

  private static class BandwidthMeasurementStandardScheme extends org.apache.thrift.scheme.StandardScheme<BandwidthMeasurement> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, BandwidthMeasurement struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SOURCE_IP
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.source_ip = iprot.readString();
              struct.setSource_ipIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DESTINATION_IP
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.destination_ip = iprot.readString();
              struct.setDestination_ipIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // BANDWIDTH
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.bandwidth = iprot.readDouble();
              struct.setBandwidthIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, BandwidthMeasurement struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.source_ip != null) {
        oprot.writeFieldBegin(SOURCE_IP_FIELD_DESC);
        oprot.writeString(struct.source_ip);
        oprot.writeFieldEnd();
      }
      if (struct.destination_ip != null) {
        oprot.writeFieldBegin(DESTINATION_IP_FIELD_DESC);
        oprot.writeString(struct.destination_ip);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(BANDWIDTH_FIELD_DESC);
      oprot.writeDouble(struct.bandwidth);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class BandwidthMeasurementTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public BandwidthMeasurementTupleScheme getScheme() {
      return new BandwidthMeasurementTupleScheme();
    }
  }

  private static class BandwidthMeasurementTupleScheme extends org.apache.thrift.scheme.TupleScheme<BandwidthMeasurement> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, BandwidthMeasurement struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetSource_ip()) {
        optionals.set(0);
      }
      if (struct.isSetDestination_ip()) {
        optionals.set(1);
      }
      if (struct.isSetBandwidth()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetSource_ip()) {
        oprot.writeString(struct.source_ip);
      }
      if (struct.isSetDestination_ip()) {
        oprot.writeString(struct.destination_ip);
      }
      if (struct.isSetBandwidth()) {
        oprot.writeDouble(struct.bandwidth);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, BandwidthMeasurement struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.source_ip = iprot.readString();
        struct.setSource_ipIsSet(true);
      }
      if (incoming.get(1)) {
        struct.destination_ip = iprot.readString();
        struct.setDestination_ipIsSet(true);
      }
      if (incoming.get(2)) {
        struct.bandwidth = iprot.readDouble();
        struct.setBandwidthIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

