//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./nbt-reporting-service_types');
//HELPER FUNCTIONS AND STRUCTURES

var NBTReportingService_getSummary_args = function(args) {
};
NBTReportingService_getSummary_args.prototype = {};
NBTReportingService_getSummary_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

NBTReportingService_getSummary_args.prototype.write = function(output) {
  output.writeStructBegin('NBTReportingService_getSummary_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var NBTReportingService_getSummary_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = Thrift.copyList(args.success, [ttypes.BandwidthMeasurement]);
    }
  }
};
NBTReportingService_getSummary_result.prototype = {};
NBTReportingService_getSummary_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size0 = 0;
        var _rtmp34;
        this.success = [];
        var _etype3 = 0;
        _rtmp34 = input.readListBegin();
        _etype3 = _rtmp34.etype;
        _size0 = _rtmp34.size;
        for (var _i5 = 0; _i5 < _size0; ++_i5)
        {
          var elem6 = null;
          elem6 = new ttypes.BandwidthMeasurement();
          elem6.read(input);
          this.success.push(elem6);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

NBTReportingService_getSummary_result.prototype.write = function(output) {
  output.writeStructBegin('NBTReportingService_getSummary_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter7 in this.success)
    {
      if (this.success.hasOwnProperty(iter7))
      {
        iter7 = this.success[iter7];
        iter7.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var NBTReportingServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
NBTReportingServiceClient.prototype = {};
NBTReportingServiceClient.prototype.seqid = function() { return this._seqid; };
NBTReportingServiceClient.prototype.new_seqid = function() { return this._seqid += 1; };
NBTReportingServiceClient.prototype.getSummary = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getSummary();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getSummary();
  }
};

NBTReportingServiceClient.prototype.send_getSummary = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getSummary', Thrift.MessageType.CALL, this.seqid());
  var args = new NBTReportingService_getSummary_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

NBTReportingServiceClient.prototype.recv_getSummary = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new NBTReportingService_getSummary_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getSummary failed: unknown result');
};
var NBTReportingServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler;
}
;
NBTReportingServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}
;
NBTReportingServiceProcessor.prototype.process_getSummary = function(seqid, input, output) {
  var args = new NBTReportingService_getSummary_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getSummary.length === 0) {
    Q.fcall(this._handler.getSummary)
      .then(function(result) {
        var result_obj = new NBTReportingService_getSummary_result({success: result});
        output.writeMessageBegin("getSummary", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getSummary", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getSummary(function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new NBTReportingService_getSummary_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("getSummary", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getSummary", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
